### ISSUE TITLE
Phân tích user sinh viên

### ISSUE THREAD

**Issue by sakifire** [sakifire/Ung_dung_diem_danh_trong_lop_hoc#5]
- Tra cứu thời khóa biểu
- Tra cứu lịch sử đăng nhập, điểm danh của mình theo thời gian cụ thể
- Yêu cầu về đổi lớp học theo mong muốn
- Đóng góp ý kiến về ban quản lý, giáo viên

**Comment by QuocToan2402** [comment]
Có thể gửi lí do xin nghỉ tới giảng viên
