### ISSUE TITLE
Phân tích các yêu cầu về việc điểm danh

### ISSUE THREAD

**Issue by sakifire** [sakifire/Ung_dung_diem_danh_trong_lop_hoc#6]
- Điểm danh qua khuôn mặt
- Điểm danh qua hình ảnh
- Điểm danh qua đăng nhập tài khoản tại thiết bị
- Điểm danh qua thẻ sinh viên, thẻ giáo viên, thẻ nhân viên

**Comment by QuocToan2402** [comment]
Điểm danh xong ghi dữ liệu và có thể xuất ra file excel cho dễ quản lí.
Sinh viên/ giảng viên có thể tra cứu thông tin điểm danh của buổi học.

**Comment by QuocToan2402** [comment]
- Điểm danh nhận diện các khuôn mặt có trong lớp trực tiếp từ camera.
- Điểm danh bằng hình ảnh: điểm danh qua ảnh chụp lớp học nếu không có camera
-
